# NOTE: Do not use 1e-6 format because this is reqognized as a string

# Framework Settings
pub_on_prop: true
use_ros_time_now: false
verbose: false
verbose_out_of_order: true
discard_ooo_prop_meas: false
pub_cov: true
pub_path: false
buffer_size: 2000

# Ros Settings
use_tcpnodelay: true
bypass_init_service: false

pub_cb_buffer_size: 1
sub_imu_cb_buffer_size: 200
sub_sensor_cb_buffer_size: 1

# Sensor Settings
gyro_rate_noise: 35.2e-04 # 20*1.7600e-04  # Noise STD [rad/s]
gyro_bias_noise: 60.0e-06 # 20*3.0000e-06
acc_noise: 173.6e-04      # 20*8.6800e-04  # Noise STD [m/s^2]
acc_bias_noise: 30.0e-05  # 20*1.5000e-05

# Core state covariance p,v,q,bw,ba
core_init_cov_p: [0.5,0.5,0.5]
core_init_cov_v: [0.3,0.3,0.3]
core_init_cov_q: [0.1218,0.1218,0.1218] # 20degree
core_init_cov_bw: [0.0076,0.0076,0.0076]
core_init_cov_ba: [0.01,0.01,0.01]

# Pose1 sensor settings
pose1_pos_meas_noise: [0.05,0.05,0.05]
pose1_rot_meas_noise: [0.0873,0.0873,0.0873] # 5*pi/180
pose1_cal_p_ip: [-0.1251, 0.0373, 0.1019]
pose1_cal_q_ip: [0.3827, 0, 0, -0.9239] #w,x,y,z
pose1_state_init_cov: [0.0025, 0.0025, 0.0025, 0.068534877, 0.068534877, 0.068534877] #0.5cm and 1 deg #position[3], rot[3]
