---
  # gyr_thr: 100
  # acc_thr: 0.02
  # enc_thr: 0.0001

  gyr_thr: 0
  acc_thr: 0
  enc_thr: 0.0001

  enc_window_len: 100
  imu_window_len: 400

  eq_covariance:
    rows: 6
    cols: 6
    data: [0.5, 0.0, 0.0, 0.0, 0.0, 0.0,
           0.0, 0.5, 0.0, 0.0, 0.0, 0.0,
           0.0, 0.0, 0.02, 0.0, 0.0, 0.0,
           0.0, 0.0, 0.0, 1.1, 0.0, 0.0,
           0.0, 0.0, 0.0, 0.0, 1.1, 0.0,
           0.0, 0.0, 0.0, 0.0, 0.0, 1.1]
           # std dev: 0.05 in p and 5*(pi/180) in q
           # 0.0001
           # 0.0025

  non_eq_covariance:
    rows: 6
    cols: 6
    data: [0.5, 0.0, 0.0, 0.0, 0.0, 0.0,
           0.0, 0.5, 0.0, 0.0, 0.0, 0.0,
           0.0, 0.0, 0.02, 0.0, 0.0, 0.0,
           0.0, 0.0, 0.0, 1.1, 0.0, 0.0,
           0.0, 0.0, 0.0, 0.0, 1.1, 0.0,
           0.0, 0.0, 0.0, 0.0, 0.0, 1.1]
           # std dev: 0.05 in p and 5*(pi/180) in q
